version: '2'
services:
    nginx:
        build: .
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./conf:/etc/nginx/conf
            - ./logs:/nginx/logs
        restart: always
